### ISSUE TITLE
feat: scaffolding

### ISSUE THREAD

**Issue by matheusaraujo** [geo-quest/travel-bingo#1]
Create scaffolding for the SPA.

## Tasks

- [x] 👨‍💻 Create a React base app
- [x] 🐶 Configure `husky` + `eslint` + `lintstaged` + `conventional-commits`
- [x] 🏷️ Configure `semantic-release`
- [x] 🏃 Configure Actions
- [x] 📄 Configure GitHub Pages
- [x] Remove React logos and references
- [x] 🚀 Deploy it!

## DoD
- [x] Continuous deployment configured
- [x] Initial version is deployed at https://geo-quest.github.io/travel-bingo and

**Comment by matheusaraujo** [comment]
First release properly done on https://github.com/geo-quest/travel-bingo/actions/runs/10218726392
