### ISSUE TITLE
feat: refactoring to support curse and boost

### ISSUE THREAD

**Issue by rpidanny** [geo-quest/travel-bingo#35]
## Curses

The game will have 4 different types of challenges

- **Normal**
- **Curse1**: The curse the applies a multiplier to the score of the other team's next challenge
- **Curse2**: The curse that applies a basic penalty to the other team's next challenge (e.g -10pts)
- **Curse3**: The curse that doesn't effect the points but just adds some physical restrictions (e.g. can't take public transport for 1hr or can't leave a city for an hour)
- **AntiCurse4**: The curse applies a multiplier to the score of the team's on next challenge

### Event types

- **Blank**: To broadcast messages by the admin

### Effects of curses

If a team choses to use a curse, if they win the challenge, the curse will be applied to the other team. If they lose the challenge, the curse will be applied to them.

> We also need to add some marker in the bingo board to show that the challenge is of type curse.

#### Note

we can use the existing `point` field to store the multiplier or the penalty.

#### Nice to have features

- Show timeline on the run page (in a new tab) to show all the events of the game (challenges completed, curses applied, etc)
- Show timeline on the team's page to show all the events of the team (challenges completed, curses applied, etc) on the bottom of the bingo board?

## Tasks

- [x] Change data model to have `events` array on `RunGameData` + update the `calculateScore` method 
  - https://github.com/geo-quest/travel-bingo/pull/47
- [x] Update the Bingo Board to display curses on a different way
  - https://github.com/geo-quest/travel-bingo/pull/47
- [x] Update Game page to display the events
  - https://github.com/geo-quest/travel-bingo/pull/47
- [x] Update Team page to display the events
  - https://github.com/geo-quest/travel-bingo/pull/47

**Comment by matheusaraujo** [comment]
I'll split this issue in 5 branches/PRs:
1. Change data model to have `events` array on `RunGameData` + update the `calculateScore` method
2. Update the `calculateScore` to considering Curses 
3. Update the Bingo Board to display curses on a different way
4. Update Game page to display the events
5. Update Team page to display the events

**Comment by matheusaraujo** [comment]
```json
{
    event: "challenge_solved",
    team: "teamA",
    place: "utrecht",
    time: "now"
}

=>

{
  event: "start",
  state: [
    {team: "TeamA", points: 30, cursed_teams: ["teamB"], first_challenge: true}
  ]
}
{
    event: "challenge_solved",
    team: "teamA",
    place: "utrecht",
    time: "now",
    rule_applied: "first_challenge" // curse_1, first_time_on_place, 
    details: {
      cursed_team: "teamB"
    }
    points: 30,
    state: [
      {team: "TeamA", points: 30, cursed_teams: ["teamB"], first_challenge: true}
    ]
},


```

**Comment by matheusaraujo** [comment]
For now, we're gonna implement one single type of `curse` and one type of `boost`
- Curse1: The curse the applies a multiplier to the score of the other team's next challenge
- AntiCurse4: The curse applies a multiplier to the score of the team's on next challenge

I'm gonna create another issues for that and close this one.
